---
title: "Examples"
author: "Simon Kucharsky"
date: "`r Sys.Date()`"
output: 
  rmarkdown::github_document:
    pandoc_args: --webtex
    toc: true
bibliography: ["`r here::here('bibliography.bib')`", "`r here::here('packages.bib')`"]
csl: "`r here::here('apa.csl')`"
---

This file serves as a supplement to the article "Dynamic models of eye movements" and provides step by step explanation of the building and implementation of the modelling framework of the joint distribution of fixation locations and fixation durations.

In this folder, there are additional files that go through specific examples of the model. These examples should provide some guidance in building and implementing such a model. The models are implemented in Stan [@carpenter2017stan] in combination with the R package rstan [@R-rstan].

# Principled Bayesian modeling

Here, we summarise several criteria and approaches we used while building and validating our model, following general reccomendations for Bayesian modeling, see @schad2019principled.

## Prior predictives

Each of the models is parametrized with several parameters, some of which do, and other do not have clear physical interpretation. 

## Computational faithfullness

We check whether the Bayesian inference for the implemented model is self consistent, i.e., whether the Bayesian updating of the prior leads to correct posteriors. We check that by conducting simulation-based calibration [@talts2018sbc].

## Model sensitivity

We also investigate whether and to what extend are the estimates of the paramaters biased, and to what extend are data informative to specific parameters. To do this, we plot the posterior z-scores and posterior contraction against each other for all focal parameters in the model.

## Posterior predictives

Posterior predictives are a useful tool for assessing the adequacy of the model. Specifically, we can look at whether the model is able to predict specific data points, or whether it captures certain regularities in the data.

# Contents of examples

The [documents](documents/) folder contains some example files that show how to build specific versions of the model. They also demonstrate that various parts of the model were correctly implemented. Here, we list the files and provide short descriptions:

## [direction_bias](documents/direction_bias.md/)

## [direction_central_bias](documents/direction_central_bias.md)


# References
